name: CI/CD

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      deployProd:
        description: 'Deploy to Prod? [true/false]'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev namespace with Argo CD using Docker image"
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deployProd == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Manual Trigger for Prod Deployment
        run: |
          echo "Deploying to Prod namespace with Argo CD using Docker image"
