name: CI/CD

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      deployProd:
        description: 'Deploy to Prod? [true/false]'
        required: true
        default: 'false'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

      - name: Update Kubernetes deployment file
        run: |
          sed -i "s|${{ env.DOCKERHUB_USERNAME }}/myapp:.*|${{ env.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}|g" k8s/deployment.yml
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/deployment.yml
          git commit -m "Update image to ${{ github.sha }}" || exit 0  # exit 0 to avoid failure if no changes
          git push

  deploy:
    needs: build-and-update
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || (github.ref == 'refs/heads/main' && ${{ github.event.inputs.deployProd }} == 'true')
    steps:
      - uses: actions/checkout@v2
      - name: Notify Argo CD to sync
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "Notify Argo CD to sync Dev environment"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Notify Argo CD to sync Prod environment"
          fi
