name: CI/CD

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important pour permettre l'accès à l'ensemble du repository si nécessaire

      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

      - name: Update Kubernetes deployment file
        if: github.ref == 'refs/heads/dev'
        run: |
          sed -i "s|starman0812/myapp:.*|starman0812/myapp:${{ github.sha }}|g" k8s/deployment.yml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/deployment.yml
          git commit -m "Update Kubernetes deployment to ${{ github.sha }}"

      - name: Push changes
        run: |
          git push origin update-kube-${{ github.sha }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-kube-${{ github.sha }}
          title: "Update Kubernetes configuration"
          body: "Update the Kubernetes deployment to use the new Docker image tag."
          base: "dev"
          labels: "automerge"
